### ISSUE TITLE
exception processing test with global setup code

### ISSUE THREAD

**Issue by tomasohara** [LimaBD/batspp#51]
This seems to be related to #41 (e.g., a regression perhaps):

```
$ cat simple-alias-test.batspp
# Simple alias test

# Global Setup
$ alias count-words='wc -w'

# Test word count
$ echo abc def ghi | count-words
3
$ batspp simple-alias-test.batspp
...
Exception: Setup "test of line 4" referenced before assignment.

$ batspp --version
Batspp version 2.2.0
```

This also occurs with the devel branch.

**Comment by LimaBD** [comment]
Fixed!, the problem was that the global setups were expecting directives in the form of `# Setup` and not `# Global Setup`, added global tokens to the grammar.
